/**
 * Templates for the saifctl feature dir saifdocs emits.
 *
 * Each saifdocs run produces one timestamped feature dir containing:
 *   - feature.yml (declares the audit critic, defaults)
 *   - plan.md     (run metadata: when, what, how to invoke saifctl)
 *   - critics/audit.md (mustache template; doc-quality discover prompt)
 *   - phases/NNNN-<slug>/spec.md (per-page; rendered by callers)
 *   - phases/NNNN-<slug>/tests/public/output.spec.ts (vitest spec
 *     gating "the doc page was written and is non-empty")
 *
 * Saifctl's per-phase test contract is the test-profile-shaped spec file
 * (vitest by default) under `phases/<id>/tests/{public,hidden}/`, NOT a
 * bash gate script. The compiler auto-wires `testScope.include = [phase
 * tests dir]` for each phase's implementer subtask, so the spec is
 * scoped to the phase that produced it.
 */

import type { OutputType } from '../manifest/types.js';

/** Render `feature.yml` (saifctl phases-and-critics config). */
export function renderFeatureYml(): string {
  return `# Generated by saifdocs.
# Each phase generates one documentation page; the \`audit\` critic
# reviews each page after writing.

critics:
  - { id: audit, rounds: 1 }

tests:
  mutable: false
`;
}

/** Render the run-summary `plan.md`. */
export function renderPlanMd(opts: {
  featureId: string;
  generatedAt: Date;
  saifdocsVersion: string;
  totalPhases: number;
  byType: Partial<Record<OutputType, number>>;
}): string {
  const isoUtc = opts.generatedAt.toISOString();
  const typeBreakdown = Object.entries(opts.byType)
    .filter(([, n]) => (n ?? 0) > 0)
    .map(([t, n]) => `- ${n} ${t}`)
    .join('\n');

  return `# ${opts.featureId} — run plan

Generated by **saifdocs** v${opts.saifdocsVersion} at \`${isoUtc}\`.

This feature was emitted as a saifctl phases-and-critics tree. Each phase
generates **one documentation page**; the \`audit\` critic reviews each page
in a fresh LLM context after the implementer finishes.

## Run summary

- **Feature id:** \`${opts.featureId}\`
- **Phases:** ${opts.totalPhases} (one per file-to-generate)
- **Breakdown by type:**

${typeBreakdown}

## How to run this feature

From the project root, with \`saifctl\` installed:

\`\`\`bash
saifctl feat run --feature ${opts.featureId}
\`\`\`

## Re-emitting

Each \`saifdocs gen\` produces a fresh timestamped feature dir; multiple
runs accumulate side-by-side under \`saifctl/features/\` (e.g. for monthly
documentation refresh, before/after snapshots). To regenerate in place,
pass \`--feature-id <stable-id>\` to \`saifdocs gen\`.
`;
}

/**
 * Render the `audit` critic discover prompt. Uses saifctl's mustache template
 * vocabulary: `{{phase.id}}`, `{{phase.spec}}`, `{{feature.name}}`,
 * `{{critic.findingsPath}}`, etc. (see saifctl's phases-and-critics §4.2).
 *
 * Tuned for documentation review: omissions, false claims, drift from
 * source, diátaxis adherence, tone.
 */
export function renderAuditCriticMd(): string {
  return `You are running as critic \`{{critic.id}}\` (round \`{{critic.round}}\` of \`{{critic.totalRounds}}\`)
for phase \`{{phase.id}}\` of feature \`{{feature.name}}\`.

This is the **discover** step (\`{{critic.step}}\`). Your job is to find issues
in the documentation page produced by this phase and write them to
\`{{critic.findingsPath}}\`. **Do NOT modify code or docs in this step** — a
separate fix step will read your findings and apply them.

The phase spec at \`{{phase.spec}}\` describes what was supposed to be
written. The implementer's diff for this phase is the working-tree history
since \`{{phase.baseRef}}\`. Inspect with:

    git log {{phase.baseRef}}..HEAD
    git diff {{phase.baseRef}}..HEAD

Saifdocs generates documentation pages from a docspec; the implementer
agent had access to specific source files, rules, and templates listed in
the phase spec under "Files to read first." Cross-reference what the diff
contains against what the docspec asked for. Patterns to look out for:

- **Omissions vs. the docspec.** The phase spec lists files the implementer
  was told to read. Did the diff reflect every requirement those files
  imply? Did it skip a CLI flag, a configuration field, an exception path?
- **False claims.** Comments, descriptions, or examples that don't match
  the source code. Treat any claim as suspect until you've checked it
  against the source files referenced in the phase spec.
- **Invented behavior.** Reference pages that document a flag/option that
  doesn't exist in the source; how-to steps that won't actually work.
- **Tone or rule violations.** If the phase referenced a \`rules.md\`,
  verify the page follows it (voice, code-fence style, marketing claims,
  banned phrasings).
- **Diátaxis drift.** Reference pages doing tutorial work, how-tos
  explaining concepts, tutorials skipping the practical task — each
  Diátaxis quadrant has its own discipline.
- **Stale links / dead anchors.** Cross-references to other doc pages
  that don't exist or were renamed.
- **Missing examples.** Reference pages without at least one realistic
  usage example; how-tos without a working command sequence.
- **Etc.** Anything else that smells like a corner cut or a hallucination.

Do a **deep analysis**. Don't stop at the first finding — this is your
one chance per round to surface everything. The fix step will only
address issues you write down here, so anything you skip survives into
the next phase.

Write your findings to \`{{critic.findingsPath}}\` as a markdown checklist:

    - [ ] <file:line> — <one-line description>
          <one-paragraph explanation of why and what to do>

If you find no issues, write exactly \`no findings\` to that file
(case-insensitive). Either way, the file MUST be created.

This is round {{critic.round}}/{{critic.totalRounds}} — subsequent rounds
will see prior fixes via \`git log\`. After the fix step's tests pass,
saifctl deletes \`{{critic.findingsPath}}\`, so previous findings cannot
leak into the next round's discover prompt.
`;
}

/**
 * Render the per-phase output spec (`phases/<id>/tests/public/output.spec.ts`).
 *
 * Vitest runs in the test-runner container; the doc page lives on the
 * staging container's `/workspace/<workspaceRelOutputPath>`. The spec
 * exec's into staging via the saifctl HTTP sidecar (`SAIFCTL_SIDECAR_URL`)
 * to verify three things:
 *
 *   1. the output file exists,
 *   2. the output file is non-empty,
 *   3. the output file has body content beyond any YAML frontmatter
 *      (catches the "skeleton-only" failure mode where the agent writes
 *      just a frontmatter block).
 *
 * The spec is intentionally self-contained — no `helpers.ts` import — so
 * each phase only emits one file under `tests/public/`. Saifctl's
 * test-scope merger wires this into the merged `/tests` mount under a
 * label that carries the spec alone.
 *
 * `workspaceRelOutputPath` is the project-relative path to the doc file,
 * e.g. `docs/references/cli-flags.md`. It's interpolated as a string
 * literal, single-quote escaped to neutralize accidental quote chars.
 */
export function renderOutputSpec(workspaceRelOutputPath: string): string {
  const safePath = workspaceRelOutputPath.replace(/\\/g, '\\\\').replace(/'/g, `\\'`);
  return `// Generated by saifdocs. Gates "the agent wrote the expected doc page".
//
// Runs in the saifctl test-runner container (vitest); reaches into the
// staging container via the HTTP sidecar that saifctl injects at
// SAIFCTL_SIDECAR_URL. Three structural assertions: file exists, is
// non-empty, has body content beyond any YAML frontmatter. Doc-quality
// review happens in the \`audit\` critic — this spec is just a baseline
// "the deliverable is on disk" check.
import { describe, expect, it } from 'vitest';

const OUTPUT = '/workspace/${safePath}';

interface SidecarResult {
  stdout: string;
  stderr: string;
  exitCode: number;
}

async function exec(cmd: string, args: string[] = []): Promise<SidecarResult> {
  const url = process.env.SAIFCTL_SIDECAR_URL ?? 'http://localhost:8080/exec';
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ cmd, args }),
  });
  if (!res.ok) throw new Error(\`sidecar \${cmd}: HTTP \${res.status}\`);
  return res.json() as Promise<SidecarResult>;
}

// Loose YAML-frontmatter detector. The earlier awk-based check tripped a
// POSIX awk gotcha: \`exit 0\` from a rule routes through END, and an
// END that calls \`exit 1\` overrides — so the spec failed even when a
// body line WAS printed. Read the file via \`cat\` and parse in JS;
// no awk dialects, no exit-status overrides, easier to read.
function stripLeadingFrontmatter(content: string): string {
  return content.replace(/^---\\r?\\n[\\s\\S]*?\\r?\\n---\\r?\\n?/, '');
}

describe(\`saifdocs output: ${safePath}\`, () => {
  it('file exists', async () => {
    const r = await exec('test', ['-f', OUTPUT]);
    expect(r.exitCode, \`expected output not found at \${OUTPUT}\`).toBe(0);
  });

  it('file is non-empty', async () => {
    const r = await exec('test', ['-s', OUTPUT]);
    expect(r.exitCode, \`output file is empty at \${OUTPUT}\`).toBe(0);
  });

  it('file has body content beyond frontmatter', async () => {
    const r = await exec('cat', [OUTPUT]);
    expect(r.exitCode, \`cat \${OUTPUT} failed: \${r.stderr}\`).toBe(0);
    const body = stripLeadingFrontmatter(r.stdout).trim();
    expect(
      body.length,
      \`output has no body content at \${OUTPUT} (after stripping any YAML frontmatter)\`,
    ).toBeGreaterThan(0);
  });
});
`;
}
