/**
 * Templates for the saifctl feature dir saifdocs emits.
 *
 * Each saifdocs run produces one timestamped feature dir containing:
 *   - feature.yml (declares the audit critic, defaults)
 *   - plan.md     (run metadata: when, what, how to invoke saifctl)
 *   - critics/audit.md (mustache template; doc-quality discover prompt)
 *   - phases/NNNN-<slug>/spec.md (per-page; rendered by callers)
 *   - phases/NNNN-<slug>/tests/gate.sh (per-page output check)
 */

import type { OutputType } from '../manifest/types.js';

/** Render `feature.yml` (saifctl phases-and-critics config). */
export function renderFeatureYml(): string {
  return `# Generated by saifdocs.
# Each phase generates one documentation page; the \`audit\` critic
# reviews each page after writing.

critics:
  - { id: audit, rounds: 1 }

tests:
  mutable: false
`;
}

/** Render the run-summary `plan.md`. */
export function renderPlanMd(opts: {
  featureId: string;
  generatedAt: Date;
  saifdocsVersion: string;
  totalPhases: number;
  byType: Partial<Record<OutputType, number>>;
}): string {
  const isoUtc = opts.generatedAt.toISOString();
  const typeBreakdown = Object.entries(opts.byType)
    .filter(([, n]) => (n ?? 0) > 0)
    .map(([t, n]) => `- ${n} ${t}`)
    .join('\n');

  return `# ${opts.featureId} — run plan

Generated by **saifdocs** v${opts.saifdocsVersion} at \`${isoUtc}\`.

This feature was emitted as a saifctl phases-and-critics tree. Each phase
generates **one documentation page**; the \`audit\` critic reviews each page
in a fresh LLM context after the implementer finishes.

## Run summary

- **Feature id:** \`${opts.featureId}\`
- **Phases:** ${opts.totalPhases} (one per file-to-generate)
- **Breakdown by type:**

${typeBreakdown}

## How to run this feature

From the project root, with \`saifctl\` installed:

\`\`\`bash
saifctl feat run --feature ${opts.featureId}
\`\`\`

## Re-emitting

Each \`saifdocs gen\` produces a fresh timestamped feature dir; multiple
runs accumulate side-by-side under \`saifctl/features/\` (e.g. for monthly
documentation refresh, before/after snapshots). To regenerate in place,
pass \`--feature-id <stable-id>\` to \`saifdocs gen\`.
`;
}

/**
 * Render the `audit` critic discover prompt. Uses saifctl's mustache template
 * vocabulary: `{{phase.id}}`, `{{phase.spec}}`, `{{feature.name}}`,
 * `{{critic.findingsPath}}`, etc. (see saifctl's phases-and-critics §4.2).
 *
 * Tuned for documentation review: omissions, false claims, drift from
 * source, diátaxis adherence, tone.
 */
export function renderAuditCriticMd(): string {
  return `You are running as critic \`{{critic.id}}\` (round \`{{critic.round}}\` of \`{{critic.totalRounds}}\`)
for phase \`{{phase.id}}\` of feature \`{{feature.name}}\`.

This is the **discover** step (\`{{critic.step}}\`). Your job is to find issues
in the documentation page produced by this phase and write them to
\`{{critic.findingsPath}}\`. **Do NOT modify code or docs in this step** — a
separate fix step will read your findings and apply them.

The phase spec at \`{{phase.spec}}\` describes what was supposed to be
written. The implementer's diff for this phase is the working-tree history
since \`{{phase.baseRef}}\`. Inspect with:

    git log {{phase.baseRef}}..HEAD
    git diff {{phase.baseRef}}..HEAD

Saifdocs generates documentation pages from a docspec; the implementer
agent had access to specific source files, rules, and templates listed in
the phase spec under "Files to read first." Cross-reference what the diff
contains against what the docspec asked for. Patterns to look out for:

- **Omissions vs. the docspec.** The phase spec lists files the implementer
  was told to read. Did the diff reflect every requirement those files
  imply? Did it skip a CLI flag, a configuration field, an exception path?
- **False claims.** Comments, descriptions, or examples that don't match
  the source code. Treat any claim as suspect until you've checked it
  against the source files referenced in the phase spec.
- **Invented behavior.** Reference pages that document a flag/option that
  doesn't exist in the source; how-to steps that won't actually work.
- **Tone or rule violations.** If the phase referenced a \`rules.md\`,
  verify the page follows it (voice, code-fence style, marketing claims,
  banned phrasings).
- **Diátaxis drift.** Reference pages doing tutorial work, how-tos
  explaining concepts, tutorials skipping the practical task — each
  Diátaxis quadrant has its own discipline.
- **Stale links / dead anchors.** Cross-references to other doc pages
  that don't exist or were renamed.
- **Missing examples.** Reference pages without at least one realistic
  usage example; how-tos without a working command sequence.
- **Etc.** Anything else that smells like a corner cut or a hallucination.

Do a **deep analysis**. Don't stop at the first finding — this is your
one chance per round to surface everything. The fix step will only
address issues you write down here, so anything you skip survives into
the next phase.

Write your findings to \`{{critic.findingsPath}}\` as a markdown checklist:

    - [ ] <file:line> — <one-line description>
          <one-paragraph explanation of why and what to do>

If you find no issues, write exactly \`no findings\` to that file
(case-insensitive). Either way, the file MUST be created.

This is round {{critic.round}}/{{critic.totalRounds}} — subsequent rounds
will see prior fixes via \`git log\`. After the fix step's tests pass,
saifctl deletes \`{{critic.findingsPath}}\`, so previous findings cannot
leak into the next round's discover prompt.
`;
}

/**
 * Render the per-phase gate script (`phases/NNNN-<slug>/tests/gate.sh`).
 * Verifies the expected output file (a) exists, (b) is non-empty, and
 * (c) parses as valid markdown (loose check: starts with text, has at
 * least one heading or paragraph).
 *
 * The path is the workspace-relative path to the doc file, e.g.
 * `docs/references/cli-flags.md`.
 */
export function renderGateScript(workspaceRelOutputPath: string): string {
  // Single-quoted shell to avoid expansion; path is validated upstream by
  // outputPathRelativeToProject() which already rejects `..` segments.
  return `#!/usr/bin/env bash
# Generated by saifdocs. Verifies the agent produced the expected file.
set -euo pipefail

OUTPUT_PATH='${workspaceRelOutputPath.replace(/'/g, `'\\''`)}'

if [[ ! -f "$OUTPUT_PATH" ]]; then
  echo "saifdocs gate: expected output not found at $OUTPUT_PATH" >&2
  exit 1
fi

if [[ ! -s "$OUTPUT_PATH" ]]; then
  echo "saifdocs gate: output file is empty at $OUTPUT_PATH" >&2
  exit 1
fi

# Loose markdown sanity check: file must contain at least one non-empty
# non-frontmatter line. (Strips a leading YAML frontmatter block, then
# requires at least one printable line.)
if ! awk '
  BEGIN { in_fm = 0; fm_seen_open = 0 }
  NR == 1 && /^---$/ { in_fm = 1; fm_seen_open = 1; next }
  in_fm && /^---$/ { in_fm = 0; next }
  in_fm { next }
  /[^[:space:]]/ { print; exit 0 }
  END { if (fm_seen_open) exit 1 }
' "$OUTPUT_PATH" > /dev/null; then
  echo "saifdocs gate: output has no body content at $OUTPUT_PATH" >&2
  exit 1
fi

echo "saifdocs gate: ok ($OUTPUT_PATH)"
exit 0
`;
}
